2018-09-18T17:34:51|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\user\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\user\eclipse-workspace\Shutter\shutter_hw.py", line 20, in connect
    self.logged_quantities['shutter_closed']=True
AttributeError: 'ShutterHW' object has no attribute 'logged_quantities'

