2019-01-23T10:15:44|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\Shutter\shutter_hw.py", line 39, in connect
    self.shutter = ShutterDevice(port = self.port.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\Shutter\shutter_device.py", line 37, in __init__
    self.ser = ser = serial.Serial(port=self.port , baudrate=19200 ,bytesize=8  #define another attribute named ser,
AttributeError: module 'serial' has no attribute 'Serial'

